name: labelmerge-v0
# name: merge-v0
obs_dim: 30
action_dim: 2
action_min: [-.3, -30]
action_max: [.3, 30]

# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.29/173747_merge_train"
# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.29/175018_merge_train"
# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.29/181911_merge_train"
# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.29/230317_merge_train"
load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.29/234111_merge_train"
# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.30/001024_merge_train"

workspace:
  _target_: workspaces.merge.MergeWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_push_train_val
  data_directory: ${env_vars.datasets.merge}
  window_size: ${window_size}
