name: merge-v0
obs_dim: 5
action_dim: 2
action_min: null
action_max: null

load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.19/113918_merge_train"

workspace:
  _target_: workspaces.merge.MergeWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_push_train_val
  data_directory: ${env_vars.datasets.merge}
  window_size: ${window_size}
