# name: labelpickplace-v0
name: pickplace-v0
obs_dim: 22
action_dim: 4
action_min: [-2,-2,-2,-2]
action_max: [2,2,2,2]


load_dir: "/home/linusjz/bet2/bet/exp_local/2024.02.05/204558_pickplace_train"        # -2(50) -1.8(70) -2 
# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.02.05/211017_pickplace_train"        # -1.7

workspace:
  _target_: workspaces.pickplace.PickPlaceWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_push_train_val
  data_directory: ${env_vars.datasets.pickplace}
  window_size: ${window_size}
