name: labelstopsign-v0
obs_dim: 6
action_dim: 1
action_min: null
action_max: null

load_dir: "/home/linusjz/bet2/bet/exp_local/2024.01.18/234304_stopsign_train"

workspace:
  _target_: workspaces.stopsign.StopSignWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_push_train_val
  data_directory: ${env_vars.datasets.stopsign}
  window_size: ${window_size}
