name: labelstopsign-v0
obs_dim: 10
action_dim: 1
action_min: [-50]
action_max: [50]

# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.02.07/014608_stopsign_train"   # -2.3
# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.02.07/124947_stopsign_train"   # 
load_dir: "/home/linusjz/bet2/bet/exp_local/2024.02.07/124913_stopsign_train"     # -2.18
# load_dir: "/home/linusjz/bet2/bet/exp_local/2024.02.07/134127_stopsign_train"       # -.2.2


workspace:
  _target_: workspaces.stopsign.StopSignWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_push_train_val
  data_directory: ${env_vars.datasets.stopsign}
  window_size: ${window_size}
