_target_: models.latent_generators.mingpt.MinGPT

discrete_input: false
input_dim: ${encoder.output_dim}

vocab_size: ???  # TBD by the discretization model.

# Architecture details
n_layer: 5
n_head: 12
n_embd: 72

block_size: ${window_size}  # Length of history/context
predict_offsets: True
offset_loss_scale: 1000000.0 
focal_loss_gamma: 3.0
action_dim: ${env.action_dim}
