_target_: models.latent_generators.mingpt.MinGPT

discrete_input: false
input_dim: ${encoder.output_dim}

vocab_size: ???  # TBD by the discretization model.

# Architecture details
n_layer: 2
n_head: 3
n_embd: 3

block_size: ${window_size}  # Length of history/context
predict_offsets: True
offset_loss_scale: 100.0     # 100000.0
focal_loss_gamma: 2.0
action_dim: ${env.action_dim}
